### ISSUE TITLE
How to get a matrix gene weights in NMF

### ISSUE THREAD

**Issue by Gandalfy** [renozao/NMF#110]
Hi renozao,

Briefly, I know NMF (non-negative matrix factorization) as modeling the matrix X of expression for g genes and s samples, constituting the product of a matrix G of g gene weights for k factors and a matrix S of s sample weights for k factors.

And I want to derive the matrix G for selecting genes with high weights for specific NMF factor (cluster). How to get this matrix in NMF()?

Thanks for help.

**Comment by renozao** [comment]
Assuming `x` is an `NMF` object (either built directly or returned by `nmf()`), you can access the G and S matrix using the functions `basis()` and `coef()`:

```R
G <- basis(x)
S <- coef(x)
```
