### ISSUE TITLE
aheatmap() color and breaks

### ISSUE THREAD

**Issue by slowkow** [renozao/NMF#12]
In the function `aheatmap()`, the `color` and `breaks` parameters are
implemented incorrectly.

My goal is to use the color black, for example, for NA (or 0) values and
palette colors for all other values. Currently, that seems to be impossible
because the `color` and `breaks` parameters do not work correctly.

This code works as expected:

```R
mat2 = matrix(runif(15), nrow=5)
aheatmap(mat2, color = 'YlOrBr:3')
```

This code produces a heatmap with 50 colors, despite my effort to get
3 colors:

```R
aheatmap(mat2,
         color = brewer.pal(n = 3, name = 'YlOrBr'))
```

This code also fails because only the first 3 of the 50 colors are used:

```R
aheatmap(mat2,
         color = brewer.pal(n = 3, name = 'YlOrBr'),
         breaks = seq(min(mat2), max(mat2), length.out = 3))
```

(Some of) the code with the incorrect implementation is in `colorcode.R`:

https://github.com/renozao/NMF/blob/master/R/colorcode.R#L213

Notice the line with `if( is_NA(n) ) n <- 50`. This ensures that the
expression `n <- length(x)` will never be executed. This explains
why I see 50 colors instead of the number I want.

**Comment by renozao** [comment]
@slowkow is the issue solved and can be closed?
Thanks

**Comment by slowkow** [comment]
Yes, thank you for the code examples! That was very helpful. I appreciate it.
