### ISSUE TITLE
feature request: add labels for annotations and ability to cut dendrogram with different colors 

### ISSUE THREAD

**Issue by jyu2012** [renozao/NMF#13]
it's really nice to see legend for column/row annotations, but once one has many column annotations, it's not easy to find corresponding annotation row for a factor/variable. Is it possible to add label for each annotation variable/factor? 

Another feature I found useful from heatmap3 package is the ability to cut dendrogram and separate clusters with different background colors. Would it be possible to add such a feature into aheatmap?

Thanks,
Jay

**Comment by premadh** [comment]
I would also want that feature of adding label for each variable or annotation factor beside the annotation. Somewhat similar to this:
![labels](https://cloud.githubusercontent.com/assets/11884112/7197059/cc29ecf4-e4e4-11e4-9dcf-854cbac63c30.png)

**Comment by jyu2012** [comment]
Exactly. thank you!

Best,

**Comment by renozao** [comment]
@premadh see argument ``labAnn`` in the branch devel.
See above for installation instructions.

**Comment by renozao** [comment]
@premadh does argument `labAnn` gives what you want?

**Comment by premadh** [comment]
Yes! Exactly, the way I wanted. Thanks  :+1:
