### ISSUE TITLE
Can't install NMF due to rngtools package

### ISSUE THREAD

**Issue by Hasani2015** [renozao/NMF#138]
Hello,

I'm trying to install NMF since two days now with no success. I used different R versions (3.4.3, 3.4.4, 3.5.1) and different installing commands with no success. `install.packages("NMF", repos = "http://R-Forge.R-project.org"), install.packages("NMF"), R CMD INSTALL NMF_0.21.0.tar.gz`

The error is over and over `ERROR: dependency ‘rngtools’ is not available for package ‘NMF’`
when I tried to install the package itself (using install.packages) I get `package ‘rngtools’ is not available (for R version XXX)` 

Any idea how to solve it?

**Comment by renozao** [comment]
Due to a change in RNG handling in R 3.6, the package has been made dependent on this version and above.
I still haven't found the time to deal it, but will look into a way to keep it backward-compatible.
