### ISSUE TITLE
R CMD check failures with stringr 1.0.0

### ISSUE THREAD

**Issue by hadley** [renozao/NMF#32]
Could you please take a look? 

```
checking dependencies in R code ... NOTE
'library' or 'require' calls in package code:
  ‘Biobase’ ‘bigmemory’ ‘devtools’ ‘knitr’ ‘synchronicity’
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.
```
```
checking R code for possible problems ... NOTE
.wrapResult: no visible global function definition for ‘exprs’
devnmf: no visible global function definition for ‘load_all’
nmfReport: no visible global function definition for ‘knit2html’
posICA: no visible binding for global variable ‘fastICA’
posICA: no visible global function definition for ‘fastICA’
runit.lsnmf: no visible global function definition for ‘checkTrue’
setupLibPaths: no visible global function definition for ‘load_all’
test.match_atrack : .check: no visible global function definition for
  ‘checkEquals’
```
```
checking Rd cross-references ... NOTE
Packages unavailable to check Rd xrefs: ‘Biobase’, ‘RcppOctave’
```
```
checking data for non-ASCII characters ... NOTE
  Error in .requirePackage(package) : 
    unable to find required package 'Biobase'
  Calls: <Anonymous> ... .extendsForS3 -> extends -> getClassDef -> .requirePackage
  Execution halted
```
```
checking examples ... ERROR
Running examples in ‘NMF-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: NMF-package
> ### Title: Algorithms and framework for Nonnegative Matrix Factorization
> ###   (NMF).
> ### Aliases: NMF NMF-package
> ### Keywords: package
> 
> ### ** Examples
> 
> ## Don't show: 
> # roxygen generated flag
> options(R_CHECK_RUNNING_EXAMPLES_=TRUE)
> ## End Don't show
> 
> # generate a synthetic dataset with known classes
> n <- 50; counts <- c(5, 5, 8);
> V <- syntheticNMF(n, counts)
> 
> # perform a 3-rank NMF using the default algorithm
> res <- nmf(V, 3)
> 
> basismap(res)
Error in process_tracks(x, tracks, annRow, annCol) : 
  Invalid special annotation track name ['basis']. Should partially match one of 'basis', ':basis', 'basis:'.
Calls: basismap -> basismap -> .local -> process_tracks
Execution halted
```

**Comment by renozao** [comment]
Hi,

from my test this is the same issue as #24, with NA values returned where they used to be an empty string ``""``.

**Comment by hadley** [comment]
Ah bummer, I thought that would've been fixed upstream by now. I'll look into it.

**Comment by hadley** [comment]
Ah oops, it was my mistake - I fixed `str_match_all()` but missed `str_match()`. Can you please test again with the latest version of stringr?

**Comment by renozao** [comment]
My test case is the following, which reproduces what is done in ``NMF::basismap``

```R
str_match("abcd", "^(:)?([^:]*)(:)?$")
```

I get the error:

```R
Error in stri_match_first_regex(string, pattern, opts_regex = attr(pattern,  : 
  unused argument (cg_missing = "")

```

**Comment by hadley** [comment]
Do you have the latest stringi installed?

**Comment by hadley** [comment]
Hmmmm, looking at this more, I think I'm going to make this case return NA - it's more consistent with other match failures and stringi doesn't have quite the flexibility needed to make this work in this one case.

**Comment by renozao** [comment]
I don't know if this should be considered as a match failure, since the pattern contains an optional group, which I believe should match the empty string.

This would have quite a big side effect I think. Because the current behavior enables to reconstruct -- possibly partially -- the original string by pasting the different groups, including the empty ones.

Besides, returning NA would mean that ``str_match("", ".?")`` would return NA, which would mean not matching, whereas it is actually a valid match:

```R
str_f <- function (string, pattern) 
{
    switch(stringr:::type.character(pattern), regex = stringi::stri_match_first_regex(string, 
        pattern, opts_regex = attr(pattern, "options")), 
        stop("Can only match regular expressions", call. = FALSE))
}

str_f("", ".?")
str_f("", "(.)?")
```

```R
> str_f("", ".?")
     [,1]
[1,] NA  
> str_f("", "(.)?")
     [,1] [,2]
[1,] NA   NA  

```

**Comment by hadley** [comment]
Unfortunately you'll have to replace the NAs with `""` yourself. I ran R CMD check on all ~200 packages that use stringr, and this introduces fewer problems than the alternative.

**Comment by renozao** [comment]
Ok. 
I find it strange that changing valid -- empty -- strings into NAs does not raise more errors though. Maybe the results are not really checked/tested by the packages.
Anyway I will do as you say.

In my example above, isn't returning ``NA`` incorrect? It is a match isn't it? 
Seems it is only an issue for the empty string:

```R
> str_f("a", "b?")
     [,1]
[1,] ""
> str_f("", "b?")
     [,1]
[1,] NA  
```

**Comment by hadley** [comment]
Optional capture groups are very rarely used.

**Comment by renozao** [comment]
I made a fix for this, but as I can see, ``str_match_all`` behaviour does not return NA, but empty strings as before. Are you planning to make it return NAs as well?

```R
> str_match(c(":base", ":a:"), "^(:)?([^:]*)(:)?$")
     [,1]    [,2] [,3]   [,4]
[1,] ":base" ":"  "base" NA  
[2,] ":a:"   ":"  "a"    ":" 
>
>
> str_match_all(c(":base", ":a:"), "^(:)?([^:]*)(:)?$")
[[1]]
     [,1]    [,2] [,3]   [,4]
[1,] ":base" ":"  "base" ""  

[[2]]
     [,1]  [,2] [,3] [,4]
[1,] ":a:" ":"  "a"  ":" 
```
