### ISSUE TITLE
NMF heatmaps error on plotting tracks

### ISSUE THREAD

**Issue by mdozmorov** [renozao/NMF#33]
The most important part of NMF, visualization, described in the http://cran.r-project.org/web/packages/NMF/vignettes/heatmaps.pdf don't work. 

Running the examples verbatim (with understanding what's going on):
install.packages("NMF")
library(NMF)
# random data that follow an 3-rank NMF model (with quite some noise: sd=2)
X <- syntheticNMF(100, 3, 20, noise = 2)
# row annotations and covariates
n <- nrow(X)
d <- rnorm(n)
e <- unlist(mapply(rep, c("X", "Y", "Z"), 10))
e <- c(e, rep(NA, n - length(e)))
rdata <- data.frame(Var = d, Type = e)
# column annotations and covariates
p <- ncol(X)
a <- sample(c("alpha", "beta", "gamma"), p, replace = TRUE)
# define covariates: true groups and some numeric variable
c <- rnorm(p)
# gather them in a data.frame
covariates <- data.frame(a, X$pData, c)
res <- nmf(X, 3, nrun = 10)
# coefmap from multiple run fit: includes a consensus track
coefmap(res)

generates

Error in process_tracks(x, tracks, annRow, annCol) : 
  Invalid special annotation track name ['basis', 'consensus:']. Should partially match one of 'basis', 'consensus:', ':basis', 'basis:'.

This is strange, because the error says annotation track name IS 'basis'. 'basismap' generates the same error. Obviously, coefmap(res, tracks=NA) works, but the tracks are the most important. 

Usual sessionInfo()

R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  graphics  grDevices datasets  utils     stats     methods   base     

other attached packages:
 [1] doParallel_1.0.8     iterators_1.0.7      foreach_1.4.2        NMF_0.20.5           Biobase_2.26.0       BiocGenerics_0.12.1 
 [7] cluster_2.0.1        rngtools_1.2.4       pkgmaker_0.22        registry_0.2         ggplot2_1.0.1        dplyr_0.4.1         
[13] BiocInstaller_1.16.4

loaded via a namespace (and not attached):
 [1] assertthat_0.1     codetools_0.2-11   colorspace_1.2-6   compiler_3.1.2     DBI_0.3.1          digest_0.6.8       grid_3.1.2        
 [8] gridBase_0.4-7     gtable_0.1.2       magrittr_1.5       MASS_7.3-40        munsell_0.4.2      plyr_1.8.2         proto_0.3-10      
[15] RColorBrewer_1.1-2 Rcpp_0.11.6        reshape2_1.4.1     scales_0.2.4       stringi_0.4-1      stringr_1.0.0      tools_3.1.2       
[22] xtable_1.7-4

**Comment by renozao** [comment]
This is due to the latest release of stringr, which changed the result form
from some regular expression patterns.
Will put out a fix for this in the devel branch.

If this is an emergency, please downgrade to the previous stringr version
(from archives on CRAN).

Thanks.

**Comment by mdozmorov** [comment]
Thanks, Renaud, it works. Downgrading to http://cran.r-project.org/src/contrib/Archive/stringr/stringr_0.6.2.tar.gz helped. Hope it'll be an easy fix for you.

Closing this issue, as Hadley already reported this.

**Comment by renozao** [comment]
This should now be fixed in both master and devel branch.
Can you please install from github and check if all is fine on your side?
Thanks

**Comment by mdozmorov** [comment]
It works, with the latest 'stringr' package. Had to do:

devtools::install_github("renozao/pkgmaker", ref="develop")
devtools::install_github("renozao/NMF")

as the latest version requires pkgmaker >=0.25.7, and CRAN has 0.22.

Thanks, Renaud, will be testing.
