### ISSUE TITLE
installation from github fails

### ISSUE THREAD

**Issue by roryk** [renozao/NMF#34]
Hi @renozao,

Installation from github forces me to install pkgmaker from CRAN, which is out of date for OSX so NMF can't be installed. If I install pkgmaker from github and then install NMF from github to pull in the stringr fixes, the NMF install forces a reinstall of the outdated pkgmaker from CRAN. NMF seems like is broken using stringr 1.0, so I'm a little bit stuck. Do you have a suggestion for a workaround? Thanks!

**Comment by renozao** [comment]
You should be able to install both packages from github:

install_github('renozao/pkgmaker')
install_github('renozao/NMF')

**Comment by roryk** [comment]
Hi @renozao,

Sorry, my bug report sucked and wasn't clear. When I do that, NMF installs the old version of pkgmaker anyway:

```
> install_github('renozao/pkgmaker')
Downloading github repo renozao/pkgmaker@master
Installing pkgmaker
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/z6/vlq46wcn68d_knbqlyzd__w40000gn/T/Rtmp9eagd6/devtools9a1021ad68ef/renozao-pkgmaker-ff2ba9e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests

* installing *source* package ‘pkgmaker’ ...
** R
** inst
** tests
** preparing package for lazy loading
Creating meta registry in package 'pkgmaker' ... OK
Creating registry 'extra_handler' in package 'pkgmaker' ... OK
Creating registry 'extra_action' in package 'pkgmaker' ... OK
Registering extra handler 'install.packages' [function] ... OK
** help
*** installing help indices
** building package indices
** installing vignettes
   ‘pkgmaker-unitTests.Rnw’
   ‘pkgmaker.Rnw’
** testing if installed package can be loaded
* DONE (pkgmaker)
> library(pkgmaker)
Loading required package: registry
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] pkgmaker_0.24  registry_0.2   devtools_1.7.0

loaded via a namespace (and not attached):
 [1] bitops_1.0-6     codetools_0.2-11 digest_0.6.8     evaluate_0.6
 [5] formatR_1.1      httr_0.6.1       knitr_1.9        magrittr_1.5
 [9] RCurl_1.95-4.5   stringi_0.4-1    stringr_1.0.0    tools_3.1.2
[13] xtable_1.7-4
>
```
> install_github('renozao/NMF')
Downloading github repo renozao/NMF@master
Installing NMF
Installing dependencies for NMF:
pkgmaker
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/pkgmaker_0.22.tgz'
Content type 'application/x-gzip' length 562133 bytes (548 Kb)
opened URL
==================================================
downloaded 548 Kb


The downloaded binary packages are in
	/var/folders/z6/vlq46wcn68d_knbqlyzd__w40000gn/T//RtmpbghFmc/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/z6/vlq46wcn68d_knbqlyzd__w40000gn/T/RtmpbghFmc/devtools9a6f414d13c5/renozao-NMF-539ca24'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests

* installing *source* package ‘NMF’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c distance.cpp -o distance.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c divergence.cpp -o divergence.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c euclidean.cpp -o euclidean.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c utils.cpp -o utils.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o NMF.so distance.o divergence.o euclidean.o utils.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/NMF/libs
** R
** data
** demo
** inst
** tests
** preparing package for lazy loading
Error : package ‘pkgmaker’ 0.22 was found, but >= 0.25.7 is required by ‘NMF’
ERROR: lazy loading failed for package ‘NMF’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/NMF’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/NMF’
Error: Command failed (1)
```

I think it might be because the version n pkgmaker from github is set as pkgmaker_0.24 , which is less than the required version so it gets re-downloaded, maybe?

**Comment by renozao** [comment]
Try from the devel branches:

install_github('renozao/pkgmaker', ref = 'develop')
install_github('renozao/NMF')
# or for other fixes and features
# install_github('renozao/NMF', ref = 'devel')

**Comment by renozao** [comment]
@roryk did this solve your problem?

**Comment by roryk** [comment]
Hi @renozao,

Sorry for not following up, I suck. Yup, installing from the development branch did the trick. Thank you very much!

**Comment by omelnikov** [comment]
The second instruction (devel install) worked for me too, on 
```
Windows 7, i386-w64-mingw32            
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch
```
I upgraded from `NMF 0.20.6` to `0.23.4`
