### ISSUE TITLE
summary(NMF.models) does not return "cophenetic"

### ISSUE THREAD

**Issue by naarkhoo** [renozao/NMF#36]
I hope this issue is not related to my previous post. I see, the summary(NMF.models) does not return "cophenetic" score;

I build my NMF object as following,
     NMF.models <- nmf(m.2, seq(k.min, k.max + 1, k.incr), nrun = number_of_runs, method="brunet", seed=9876)

Also I have to say, 
for the plot I get the following warning
plot(NMF.models)
Warning message:
In .local(x, y, ...) : NMFfit object has no residuals track

I tried to calculate the cophenetic score separately,
> cophcor(NMF.models)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘cophcor’ for signature ‘"NMFfit"’

**Comment by renozao** [comment]
Are you running multiple runs (nrun > 1).
Cophenetic coefficient is only computed on the consensus matrix of
multi-run NMF.

**Comment by renozao** [comment]
Also, on a multi-rank run, the result is an S3 object of class `NMF.rank`, which is a list that contains the fitted models are returned in element `fit`:

```R
x <- rmatrix(20,10)
res <- nmf(x, 2:4, nrun = 3)
names(res$fit)
cophcor(res$fit[[1]])

# output
> names(res$fit)
[1] "2" "3" "4"
> cophcor(res$fit[[1]])
[1] 0.9555184
```
