### ISSUE TITLE
Resize row labels in heatmap 

### ISSUE THREAD

**Issue by komalsrathi** [renozao/NMF#38]
This is my code:

<code>
aheatmap(x = as.matrix(dat), scale = 'row', legend = F, fontsize = 12, cexRow = .9, cexCol = .9, main = 'Heatmap', filename = 'plot.pdf', width = 5, height = 10)
</code>

I am trying to make heatmaps of different row sizes, using the above code. When the number of rows is small (<100), the row labels are clear & big in size. But when you try to make a heatmap with many rows (>100), the row labels become really small & are almost illegible.

Also posted on: http://stackoverflow.com/questions/29678312/unable-to-resize-row-labels-in-aheatmap

**Comment by renozao** [comment]
I pushed a fix for this in the devel branch 1ac425e .

To install:
```
install_github('renozao/pkgmaker', ref = 'develop')
install_github('renozao/NMF', ref = 'devel')
```

Then try:
```
aheatmap(x = as.matrix(dat), scale = 'row', legend = F, main = 'Heatmap', filename = 'plot.pdf', width = 5, height = 10) 
```

**Comment by komalsrathi** [comment]
Hi,

I cannot access the version where you fixed this issue. Can you please link me to it? When I try to install it from Github or CRAN it is giving me the same issue as before.

--Komal


----- Original Message -----

**Comment by sriesenfeld** [comment]
Hi, I am trying to solve this same problem with row labels that are too small and do not resize in aheatmap(),  but after installing pkgmaker as above, I am running into this problem, using RStudio on my Macbook:

> install_github('renozao/NMF', ref = 'devel')
Downloading GitHub repo renozao/NMF@devel
from URL https://api.github.com/repos/renozao/NMF/zipball/devel
Error: Could not find build tools necessary to build NMF


Could you please advise me?  Here's the information about the version of R I am running:

> R.version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by renozao** [comment]
Seems that you don't have the system tools to compile packages. 
I thought that Mac R installation provided them by default, apparently not.
Maybe have a look here: http://stackoverflow.com/questions/35096233/error-could-not-find-build-tools-necessary-to-build-dplyr

**Comment by sriesenfeld** [comment]
Thanks! It turns out I had Xcode but the installation hadn't completed.
