### ISSUE TITLE
  NMF residuals: final objective value is NA

### ISSUE THREAD

**Issue by brdhungana** [renozao/NMF#41]
1. The NMF model converged in 410 iteration but yielded NA objective function value. We have been seeing this issue very often with highly sparse data. I am wondering if there is any option in the nmf()  function or specific choice of method that helps to resolve this issue. 

 
System information:
NMF_0.20.5 ; system: x86_64, linux-gnu; "R version 3.1.2 (2014-10-31)"

str(Train2_DSN)
'data.frame':	10193493 obs. of  168 variables:
 $ X00   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ X1N   : int  1 1 0 0 0 0 1 1 0 1 ...
 $ X1U   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ X1X   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ X1Y    : int  0 0 0 0 0 0 0 0 0 0 ...

system.time(NMF_res2<-nmf(Train2_DSN, rank=8, nrun=1, method="ns",  theta=0.3, seed='nndsvd'));

NMF algorithm: 'nsNMF'
NMF seeding method: nndsvd
Iterations:   50/2000 Iterations:  100/2000 Iterations:  150/2000 Iterations:  200/2000 Iterations:  250/2000 Iterations:  300/2000 Iterations:  350/2000 Iterations:  400/2000 Iterations:  400/2000 
DONE (converged at 410/2000 iterations)
     user    system   elapsed 
74499.012   200.859 74712.015 

Warning message:
In .local(x, rank, method, ...) :
  NMF residuals: final objective value is NA

**Comment by renozao** [comment]
Try with an input ``matrix``, not a ``data.frame``.

**Comment by brdhungana** [comment]
Feeding input as matrix not always helpful to this issue. I and my colleagues have run into this issue very frequently. Here is again my most recent run of NMF. I am willing to share data if you have time to dig into this issue.

> k<-6
> library(NMF)
Loading required package: pkgmaker
Loading required package: registry
Loading required package: rngtools
Loading required package: cluster
NMF - BioConductor layer [NO: missing Biobase] | Shared memory capabilities [NO: bigmemory] | Cores 15/16
  To enable the Bioconductor layer, try: install.extras('
NMF
') [with Bioconductor repository enabled]
  To enable shared memory capabilities, try: install.extras('
NMF
')
> nmf.options(debug = TRUE);
> k<-6
> system.time(NMF_OID_nsr6td3<-nmf(Train.SWDownload_3, rank=k, nrun=1, method="ns",  theta=0.3, seed='nndsvd', .option="vP8"));
# NMF call: .local(x = x, rank = rank, method = method, seed = "nndsvd", 
      nrun = 1, .options = "vP8", theta = 0.3)
NMF algorithm: 'nsNMF'
# ** Current RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 201L, ..., -1605279472L [347f9e5f876d2a7e54b6d36dd867e4fd] 
# Setting up RNG ... 
# ** Original RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 201L, ..., -1605279472L [347f9e5f876d2a7e54b6d36dd867e4fd] 
# RNG setup: standard [using current RNG]
NMF seeding method: nndsvd
DEBUG::seed -> using model parameters:
$model[1] "NMFns"$theta[1] 0.3$rank[1] 6$target[1] 0
DEBUG::nmfModel -> Instantiate NMF model:NMFns
DEBUG::nmfModel -> Set factors in model:NMFns
DEBUG::seed -> using NMF model 'NMFns'
DEBUG::seed -> use seeding method: 'nndsvd'
DEBUG::nmfModel -> Instantiate NMF model:NMFstd
DEBUG::nmfModel -> Set factors in model:NMFstd
DEBUG::nmf -> Seed is of class: 'NMFfit'
## OPTIONS:
# verbose: TRUE	| parallel.required: 8	| garbage.collect: 50	| RNGstream: TRUE
<object of class: NMFStrategyIterative>
 name: nsNMF [NMF]
 objective: 'KL' 
 model: NMFns 
 <Iterative schema>
  onInit: none
  Update: function (i, v, x, copy = FALSE, ...)
  Stop: 'connectivity'
  onReturn: none
DEBUG::Strategy Workspace -> initialize static workspace: NULL=<environment: 0xffa1510>
Iterations:  400/2000
DONE (converged at 410/2000 iterations)
DEBUG::NMFStrategyIterativeX::run -> Done
# NMF computation exit status ... OK

## Running normal exit clean up ... 
# Restoring NMF options ... OK
   user  system elapsed 
110.258   0.004 111.525 
Warning message:
In .local(x, rank, method, ...) :
  NMF residuals: final objective value is NA
> save(NMF_OID_nsr6td3, file='/home/cmanas/dhunganb/Basanta/HPEnterpriseModelingProjects/SoftwarePersonalization/TrainOIDNMFModel/NMF_OID_nsr6td3.rda');
> class(Train.SWDownload_3)
[1] "matrix"
> k<-20
> system.time(NMF_OID_nsr20td3<-nmf(Train.SWDownload_3, rank=k, nrun=1, method="ns",  theta=0.3, seed='nndsvd', .option="vP8"));
# NMF call: .local(x = x, rank = rank, method = method, seed = "nndsvd", 
      nrun = 1, .options = "vP8", theta = 0.3)
NMF algorithm: 'nsNMF'
# ** Current RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 201L, ..., -1605279472L [347f9e5f876d2a7e54b6d36dd867e4fd] 
# Setting up RNG ... 
# ** Original RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 201L, ..., -1605279472L [347f9e5f876d2a7e54b6d36dd867e4fd] 
# RNG setup: standard [using current RNG]
NMF seeding method: nndsvd
DEBUG::seed -> using model parameters:
$model[1] "NMFns"$theta[1] 0.3$rank[1] 20$target[1] 0
DEBUG::nmfModel -> Instantiate NMF model:NMFns
DEBUG::nmfModel -> Set factors in model:NMFns
DEBUG::seed -> using NMF model 'NMFns'
DEBUG::seed -> use seeding method: 'nndsvd'
DEBUG::nmfModel -> Instantiate NMF model:NMFstd
DEBUG::nmfModel -> Set factors in model:NMFstd
DEBUG::nmf -> Seed is of class: 'NMFfit'
## OPTIONS:
# verbose: TRUE	| parallel.required: 8	| garbage.collect: 50	| RNGstream: TRUE
<object of class: NMFStrategyIterative>
 name: nsNMF [NMF]
 objective: 'KL' 
 model: NMFns 
 <Iterative schema>
  onInit: none
  Update: function (i, v, x, copy = FALSE, ...)
  Stop: 'connectivity'
  onReturn: none
DEBUG::Strategy Workspace -> initialize static workspace: NULL=<environment: 0xfe7c660>
Iterations:  400/2000
DONE (converged at 410/2000 iterations)
DEBUG::NMFStrategyIterativeX::run -> Done
# NMF computation exit status ... OK

## Running normal exit clean up ... 
# Restoring NMF options ... OK
   user  system elapsed 
569.430   0.015 572.759 
Warning message:
In .local(x, rank, method, ...) :
  NMF residuals: final objective value is NA

**Comment by brdhungana** [comment]
str(Train.SWDownload_3)
 int [1:15756, 1:380] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:15756] "0000000000000000000000000000000000000000" "4951929341114630213540323831020364252500" "4960281577968307431569047035924449172300" "4977775548430838753422961963251531962700" ...
  ..$ : chr [1:380] "4AA0-2591ENW" "4AA0-4245ENW" "4AA0-4501ENW" "4AA0-4615ENW" ...
> class(Train.SWDownload_3)
[1] "matrix"
