### ISSUE TITLE
NMF temporary directory and file writing are unsuitable for Shiny apps?

### ISSUE THREAD

**Issue by VermillionAzure** [renozao/NMF#50]
I'm not exactly sure, but it appears that since NMF likes to use temporary directories, it somehow fails to give itself the permission to serialize to a file in that directory.

This also seems to be relevant: [Shiny and writing to files](https://groups.google.com/forum/#!topic/shiny-discuss/srWETT6uL-I)

**Comment by VermillionAzure** [comment]
![nmfbug](https://cloud.githubusercontent.com/assets/844699/9101330/290e7c76-3b81-11e5-9a4c-eef080e4a7b6.png)

**Comment by renozao** [comment]
Is this issue not a problem anymore?
`nmf` writes in the current directory to enable access to all workers, even when running parallel jobs that span multiple hosts (e.g. MPI workers on a cluster).

**Comment by VermillionAzure** [comment]
Sorry; I've gone a lot past my use of NMF, since the "bug" disappeared somehow. I believe one of my co-workers also found some sort of issue like this but I think it was unrelated to NMF. Either way, I'm not sure if it was even a problem with NMF at this point so I'm inclined to say nothing's wrong.

**Comment by renozao** [comment]
All good then.
Sometimes this issue would come due to disk quota/access failure.
