### ISSUE TITLE
how consensus matrix is calculated

### ISSUE THREAD

**Issue by fromdputto** [renozao/NMF#51]
How does the consensus matrix is calculated ?
I understand the part that NMF generates two matrix W and H of rank r. 
But how are we calculate consensus matrix from W and H ? 
Thanks !

**Comment by renozao** [comment]
The consensus matrix is the average connectivity matrix (from clustering based on ``H``) of multiple NMF runs. Each run gives a cluster membership for each sample (columns), from max row of each column of ``H``, which gives a connectivity matrix. The average of all connectivity matrices across runs is the consensus matrix.

**Comment by fromdputto** [comment]
From this my interpretation is "in case of small value of 'nrun' the consensus matrix can be misleading" .
Thanks for explanation.

**Comment by renozao** [comment]
Correct.
You need a reasonnable value of ``nrun`` to achieve stability of the consensus matrix.

**Comment by sdoerstling** [comment]
@renozao Is it possible to extract the average connectivity matrix based on cluster membership for each gene (row)?
