### ISSUE TITLE
NMF residuals: final objective value is NA

### ISSUE THREAD

**Issue by brdhungana** [renozao/NMF#55]
The nmf model converges but results warning message 'final objective value is NA'.  I am wondering if issue above is related to data. Earlier, you have recommended to use 'matrix' instead of data frame. It turns out, there could be more than that to resolve this issue. Looking for your advice.   I am ready to provide data set if needed.

> class(Train.SWDownload_4)
[1] "matrix"
> dim(Train.SWDownload_4)
[1] 15756   380
> str(Train.SWDownload_4)
 int [1:15756, 1:380] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:15756] "0000000000000000000000000000000000000000" "4951929341114630213540323831020364252500" "4960281577968307431569047035924449172300" "4977775548430838753422961963251531962700" ...
  ..$ : chr [1:380] "4AA0-2591ENW" "4AA0-4245ENW" "4AA0-4501ENW" "4AA0-4615ENW" ...

> k<-6
> system.time(NMF_OID_nsr6td3<-nmf(Train.SWDownload_4, rank=k, nrun=1, method="ns",  theta=0.1, seed='nndsvd', nmf.options(pbackend=NA)));
# NMF call: .local(x = x, rank = rank, method = method, seed = "nndsvd", 
      rng = ..4, nrun = 1, theta = 0.1)
NMF algorithm: 'nsNMF'
# ** Current RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 1L, ..., -326131735L [cbd726aa065c4bef16166515deaa50c5] 
# Setting up RNG ... 
# ** Original RNG settings:
# RNG kind:  Mersenne-Twister / Inversion 
# RNG state: 403L, 1L, ..., -326131735L [cbd726aa065c4bef16166515deaa50c5] 
# RNG setup: standard [using current RNG]
NMF seeding method: nndsvd
DEBUG::seed -> using model parameters:
$model[1] "NMFns"$theta[1] 0.1$rank[1] 6$target[1] 0
DEBUG::nmfModel -> Instantiate NMF model:NMFns
DEBUG::nmfModel -> Set factors in model:NMFns
DEBUG::seed -> using NMF model 'NMFns'
DEBUG::seed -> use seeding method: 'nndsvd'
DEBUG::nmfModel -> Instantiate NMF model:NMFstd
DEBUG::nmfModel -> Set factors in model:NMFstd
DEBUG::nmf -> Seed is of class: 'NMFfit'
## OPTIONS:
# garbage.collect: 50	| RNGstream: TRUE
<object of class: NMFStrategyIterative>
 name: nsNMF [NMF]
 objective: 'KL' 
 model: NMFns 
 <Iterative schema>
  onInit: none
  Update: function (i, v, x, copy = FALSE, ...)
  Stop: 'connectivity'
  onReturn: none
DEBUG::Strategy Workspace -> initialize static workspace: NULL=<environment: 0x8bb3e80>
Iterations:  400/2000
DONE (converged at 410/2000 iterations)
DEBUG::NMFStrategyIterativeX::run -> Done
# NMF computation exit status ... OK

## Running normal exit clean up ... 
# Restoring NMF options ... OK
   user  system elapsed 
109.965   0.058 110.034 
Warning message:
In .local(x, rank, method, ...) :
  NMF residuals: final objective value is NA

**Comment by renozao** [comment]
Have you looked for rows or columns that only contain 0s or NAs?

**Comment by brdhungana** [comment]
Yes, I have already filtered out those cases. Let me know if you would like to test the data and debug the issue. I could send by email. Thank you.

**Comment by renozao** [comment]
Just to exclude a data problem. Can you try running it using random seeding, e.g. with `seed = 12345` ?
Maybe the `nnsvd` seeding method creates some NA values.

**Comment by brdhungana** [comment]
It works with 'random' seed method but not with 'nnsvd'. That means I need to increase number of runs from 1 to >100. Could you please explain: under what data conditions 'nnsvd' seeding method could potentially generate NULL value. Thank you very much.
