### ISSUE TITLE
R NMF  Package

### ISSUE THREAD

**Issue by Verditer** [renozao/NMF#6]
What would be the reason that NMF method keeps complaining the below error 

Error: NMF::nmf - Input matrix x contains at least one null or NA-filled row.

Though I have double checked the matrix that I am passing for Null Values. The matrix is created from Document Term matrix which in turn was created with tm package

Cheers!
Verditer

**Comment by thomashrabe** [comment]
Thanks, that was helpful for my project, too. The error should be clearer, maybe identify the row immediately.
