### ISSUE TITLE
Problem about inconsistent between col annotation in heatmap and actual meta types

### ISSUE THREAD

**Issue by zzg2016** [renozao/NMF#64]
I was trying to generate an annotated heatmap using aheatmap function. However, when I try to plot aheatmap by calling

Rawdata=read.table("Raw_data.txt",header=T,sep="\t",row.names=1); 
Row_Anno=read.table("Row_Annotation.txt",header=T,sep="\t",row.names=1); 
Col_Anno=read.table("Col_Annotation.txt",header=T,sep="\t",row.names=1); 

aheatmap(Rawdata, color = "-RdYlBu2:100", distfun = "euclidean", hclustfun = "complete", annCol = Col_Anno, annRow = Row_Anno,scale="row"); 

I get a heatmap with inconsistent col annotations. 
![heatmap](https://cloud.githubusercontent.com/assets/18608513/14732909/50de121a-0891-11e6-8ce5-68e6718ae3cd.png)
For example, Acetobacteraceae should belong to Proteobacteria phylum (see head(Col_Anno)) but was not properly displayed by the col annotation (Firmicutes phylum) in the heatmap. I guess no link between the col names in my data (head(Rawdata)) and the col annotation file (head(Col_Anno)) may result in this issue but I do not know how to build this communication between Rawdata and Col_Anno to correct this bug.

Please give me a hand. Waiting for your reply. Thanks!

> head(Rawdata)
           Orbaceae Neisseriaceae Pseudomonadaceae Acetobacteraceae Enterobacteriaceae Lactobacillaceae
ljl_2_2B31    4e-04         0e+00           0.1862            0e+00             0.0026           0.0014
ljl_2_2B38    4e-04         6e-04           0.1974            0e+00             0.0022           0.0016
ljl_2_2B41    4e-04         0e+00           0.1952            2e-04             0.0040           0.0020
ljl_2_2B33    2e-04         2e-04           0.1894            0e+00             0.0052           0.0022
ljl_2_2B44    0e+00         2e-04           0.1808            0e+00             0.0036           0.0014
ljl_2_2B36    4e-04         4e-04           0.2232            0e+00             0.0046           0.0012
           Bacillaceae Streptococcaceae Moraxellaceae Bifidobacteriaceae Flavobacteriaceae Micrococcaceae
ljl_2_2B31      0.3820           0.2660        0.0562              0e+00            0.0224         0.0372
ljl_2_2B38      0.3874           0.2584        0.0558              0e+00            0.0192         0.0306
ljl_2_2B41      0.3790           0.2588        0.0646              0e+00            0.0166         0.0318
ljl_2_2B33      0.3784           0.2730        0.0582              0e+00            0.0182         0.0304
ljl_2_2B44      0.3794           0.2700        0.0604              0e+00            0.0246         0.0296
ljl_2_2B36      0.3754           0.2536        0.0480              2e-04            0.0214         0.0276
           Listeriaceae Sphingomonadaceae Planococcaceae Carnobacteriaceae
ljl_2_2B31       0.0238             0e+00         0.0068            0.0042
ljl_2_2B38       0.0224             2e-04         0.0078            0.0048
ljl_2_2B41       0.0260             4e-04         0.0084            0.0048
ljl_2_2B33       0.0240             0e+00         0.0054            0.0054
ljl_2_2B44       0.0256             6e-04         0.0098            0.0044
ljl_2_2B36       0.0240             2e-04         0.0090            0.0026

> head(Col_Anno)
                           Phylum               Class
Orbaceae           Proteobacteria Gammaproteobacteria
Neisseriaceae      Proteobacteria  Betaproteobacteria
Acetobacteraceae   Proteobacteria Alphaproteobacteria
Enterobacteriaceae Proteobacteria Gammaproteobacteria
Lactobacillaceae       Firmicutes             Bacilli
Bifidobacteriaceae Actinobacteria      Actinobacteria

> head(Row_Anno)
           Mate.Result
ljl_2_2B31          MS
ljl_2_2B38          MS
ljl_2_2B41          MS
ljl_2_2B33          MS
ljl_2_2B44          MS
ljl_2_2B36          MS

**Comment by zzg2016** [comment]
I have attached my dataset for generating that aheatmap as mentioned above. For this issue, these data may be directly useful.
 
[Col_Annotation.txt](https://github.com/renozao/NMF/files/233270/Col_Annotation.txt)
[Raw_data.txt](https://github.com/renozao/NMF/files/233272/Raw_data.txt)
[Row_Annotation.txt](https://github.com/renozao/NMF/files/233271/Row_Annotation.txt)

**Comment by renozao** [comment]
Which version of NMF are you using? Can you post your `sessionInfo()`?
Using stock CRAN version (0.20.6) I get the following heatmap, which I believe has correct annotations:

![clipboard](https://cloud.githubusercontent.com/assets/1070589/14779383/39cdb424-0ad8-11e6-9406-f6c1eb411b0a.png)

**Comment by zzg2016** [comment]
Dear Renozao,

I greatly appreciated your reply. Unfortunately, the heatmap still showed incorrect col annotations as you generated below.

Maybe this error is not due to different versions of NMF, because I passed this issue yesterday by keeping consistent order between colnames in rawdata matrix for heatmap and rownames in data frame file for col annotation.

Thanks again!

Best regards,

Zhigang 



�� 2016-04-25 17:24:49��"Renaud Gaujoux" <notifications@github.com> ������

**Comment by renozao** [comment]
Yes, I edited my replied just after posting it. 
The annotation data must be in the same order as the input data. Rownames are not used/matched.

**Comment by zzg2016** [comment]
It is very perfect! Thanks!


�� 2016-04-25 19:18:32��"Renaud Gaujoux" <notifications@github.com> ������
