### ISSUE TITLE
How to set flag options in "nndsvd" for seeding

### ISSUE THREAD

**Issue by wudustan** [renozao/NMF#73]
I'm trying to switch to one of the flag options: nndsvdar/nndsvda in NMF but I am not sure how to set the flag option before calling an NMF run.

**Comment by renozao** [comment]
The original parameter `flag` is implemented by argument `densify=c('none', 'average', 'random')`.
You can pass the desired values to `nmf()` by using a `list` in argument `seed` as follows:

```R
nmf(x, seed = list('nndsvd', densify = 'average'), ...)
```

**Comment by wudustan** [comment]
Thanks!
