### ISSUE TITLE
Loading NMF fails when inside a container

### ISSUE THREAD

**Issue by roelj** [renozao/NMF#75]
As requested here:
http://lists.r-forge.r-project.org/pipermail/nmf-user/2017/000056.html

NMF fails to load when it's inside a very minimal container.

```{bash}
user@container ~# R

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(NMF)
Loading required package: pkgmaker
Loading required package: registry

Attaching package: 'pkgmaker'

The following object is masked from 'package:base':

    isNamespaceLoaded

Loading required package: rngtools
Loading required package: cluster
sh: wc: command not found
Error : .onAttach failed in attachNamespace() for 'NMF', details:
  call: if (n > 2) n <- n - 1L
  error: missing value where TRUE/FALSE needed
Error: package or namespace load failed for 'NMF'
>

```

I found out that if I add `grep` and `coreutils` to the container, it works.

**Comment by renozao** [comment]
Looks like that in your setting `parallel::detectCores()` returns `NA`. 
Strange that the `grep` and `coreutils` dependencies do not come along with R installation.
My commit should fix the loading issue, by using a single core if the number of cores cannot be determined. 
Out of curiosity, how did you build the container? Is it based on rocker images?

**Comment by roelj** [comment]
I built the container using [GNU Guix](https://www.gnu.org/software/guix/):
```{bash}
$ guix environment --container --ad-hoc r r-nmf # later added grep and coreutils
```

Thanks for the fix!  That was really quick. :+1:

**Comment by renozao** [comment]
I guess you re fine now with `grep` and `coreutils`.
Otherwise, to get the fix, you'll need to install from Github, branch `devel`.

**Comment by rescuz** [comment]
could you tell me how to resolve this problem in detail?Thanks.
