### ISSUE TITLE
conflicts with DelayedArray library

### ISSUE THREAD

**Issue by rvalieris** [renozao/NMF#85]
Hello,

the nmf function uses `getGeneric("seed")`, the problem is that the [latest 0.3.5 version of DelayedArray](https://github.com/Bioconductor/DelayedArray/commit/fbc0c9a893e8ada889c3c72700021f54e2542209) it also have a "seed" generic.

See this example:
```r
> library(NMF)
> r = nmf(matrix(5,5,5), 1) # ok

> library(DelayedArray) # version 0.3.5
> r = nmf(matrix(5,5,5), 1)
Error in (function (x)  : 
  unused arguments (model = list(model = "NMFstd", rank = 1, target = 0), method = "random")

> getGeneric("seed")
standardGeneric for "seed" defined from package "DelayedArray"
```

sometimes the error is different, but I haven't figured out yet how to trigger this:

```r
Error in do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method),  : 
  'what' must be a function or character string
> traceback()
8: do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method), 
       parameters.seed))
7: .local(x, rank, method, ...)
6: nmf(x, rank, method = strategy, ...)
5: nmf(x, rank, method = strategy, ...)
[...]
```

I believe changing the call to `getGeneric("seed", package = "NMF")` should solve but I don't understand all that is going on to be honest.

**Comment by jonathanronen** [comment]
Hi
This clash is still happening in `R-3.5.2`, `NMF_0.21.0`, `DelayedArray_0.8.0`

a hack that works is `detach("package:DelayedArray")`. But if you could fix this it would be better :beers:

**Comment by PoisonAlien** [comment]
I have the same issue. Thanks @jonathanronen for the suggestion. If `SummarizedExperiment` is loaded by any package (which in-turn depends on DelayedArray) NMF fails to run.

**Comment by jonathanronen** [comment]
:fist_oncoming:
