### ISSUE TITLE
esGolub dataset

### ISSUE THREAD

**Issue by sagar-m** [renozao/NMF#87]
Hi!

Am not able to run the esGolub dataset as the Biobase package is no longer available on cran in R. Please advise!

Thanks a ton!

**Comment by renozao** [comment]
`Biobase` is a Bioconductor package, and is not hosted on CRAN.
Check there for instructions https://www.bioconductor.org/install

**Comment by sagar-m** [comment]
Hi, the following seems to work. However, is the Biobase package not
available for "Biobase"'? Thanks a ton.


library(NMF)
install.packages("Biobase")

"package ‘Biobase’ is not available (for R version 3.3.3)"
And I also got the same error for R version 3.4
