### ISSUE TITLE
sparse matrix

### ISSUE THREAD

**Issue by sagar-m** [renozao/NMF#88]
Hi Renaud,

Kindly suggest if I can run NMF with sparse matrix? I have 200,000 rows and some 36000 columns...not possible to convert into a matrix.

What should i do?

Thanks!

**Comment by renozao** [comment]
Currently the function `nmf()` does not support sparse matrices.
Adapting the current algorithms could be possible but one question is how to deal with the non-sparse product of the fitted factors `W` and `H`.
If you find/implement an algorithm that handles this case, I can integrate it into the package.
