### ISSUE TITLE
Error with sparse matrix

### ISSUE THREAD

**Issue by sdoerstling** [renozao/NMF#89]
Hi all,

I am working with a sparse non-negative matrix (null values as 0) and receive the following errors. Interestingly, if I add 1 to the entire matrix, it runs fine. Any help is greatly appreciated! Apologies if this is basic–I am new to bioinformatics.

`results <- nmf(mat, 2:6, nrun = 10, .options = "p4")`

Timing stopped at: 2.518 0.591 1.372
Timing stopped at: 2.412 0.639 1.462
Timing stopped at: 2.396 0.596 1.755
Timing stopped at: 1.513 0.442 1.257
Timing stopped at: 1.537 0.426 1.231
Error in (function (...)  : All the runs produced an error:
-#1 [r=2] -> NMF::nmf - 7/10 fit(s) threw an error.
# Error(s) thrown:
NA
-#2 [r=3] -> NMF::nmf - 8/10 fit(s) threw an error.
# Error(s) thrown:
  - run #2: non-conformable arrays
  - run #6: non-conformable arrays
-#3 [r=4] -> NMF::nmf - 7/10 fit(s) threw an error.
# Error(s) thrown:
  - run #2: non-conformable arrays
  - run #5: comparison of these types is not implemented
-#4 [r=5] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays
  - run #5: comparison of these types is not implemented
-#5 [r=6] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays

**Comment by renozao** [comment]
This was due NA values getting introduced from zero entries in the estimated product WH.
Solved by ignoring those entries in the crossproduct they are involved (treated as zero).
