### ISSUE TITLE
snmf/l algorithm, smoothness and sparseness parameters

### ISSUE THREAD

**Issue by Iftix** [renozao/NMF#97]
Hi everyone,

I am currently using the NMF package, and the snmf/l algorithm. In their article from 2007, where they explain this algorithm, Kim and Park spoke of a smoothness parameter eta and a sparseness parameter beta. I would like to know if it is possible to change these parameters ?

If yes, how can I do that?

If no (or if yes too), do you know what are the default value of these parameters ?

Thank you very much for reading me, and thank you even more if you can help me :) 

(link for the article : https://academic.oup.com/bioinformatics/article/23/12/1495/225472/Sparse-non-negative-matrix-factorizations-via)

**Comment by renozao** [comment]
Yes, you can pass those parameters to `nmf()`.
See the man page `?'SNMF/L-nmf'`

**Comment by renozao** [comment]
Yes, you can pass those parameters to `nmf()`.
See the man page `?'SNMF/L-nmf'`
